### ISSUE TITLE
能否提供pretrained weights?

### ISSUE THREAD

**Issue by yushuinanrong** [zheng-yuwei/enhanced-UGATIT#1]
@zheng-yuwei 
感谢分享你的codebase. 能否提供一些你训练好的模型weights, 方便大家快速查看结果？

**Comment by zheng-yuwei** [comment]
> @zheng-yuwei
> 感谢分享你的codebase. 能否提供一些你训练好的模型weights, 方便大家快速查看结果？

分享不了哈。
要是只是想复现全图I2IT的，好像已经有人用我库跑了。
如果是要复现固定背景的，问题也不大。
不过固定背景的我有一些idea还在实验中应该还可以获得更好的风格化效果。

**Comment by yushuinanrong** [comment]
Thanks.

**Comment by yushuinanrong** [comment]
@zheng-yuwei 
麻烦问下你有跑过全图转换的实验吗？类似风景，街景这样的图片。

**Comment by zheng-yuwei** [comment]
有呀，我博客里的变漫画不就是全图的么。。。

**Comment by yushuinanrong** [comment]
@zheng-yuwei 
了解。我比较好奇这个网络在景色图片风格转换的效果，类似AnimeGAN paper中的”新海诚化“。我打算用你的codebase跑一下这方面的实验，如果有结果我会分享出来。

**Comment by zheng-yuwei** [comment]
嗯，纯粹的风格化应该有其他更好的实现方式。这个论文重点在于形状上的变化也能hold得不错。不过很期待你尝试后的效果，等你分享～

**Comment by yushuinanrong** [comment]
@zheng-yuwei 
我试着用你的code在一个人脸/动漫脸数据集和一个自然风景数据集上面做了训练。
人脸的数据集中，真实人脸有10000张，（日本）动漫脸有5000张。大部分是frontal face。 训练了六十多万个iteration后的效果在下面，我感觉模型对保留人物性别特征，发型，肤色，配饰（眼镜等）这些细节都做的不怎么好。请问你训练的模型，有这方面的问题吗？
![face_transform](https://user-images.githubusercontent.com/17254532/132760169-4b1dfe32-f6d0-4a4b-8417-6f8524f07e98.png)

自然风景的那个数据集，动漫图片有2000张，真实图片有6000张。训练了六十多万个iteration后的效果在下面，感觉效果不太行。
![scenary_transformation](https://user-images.githubusercontent.com/17254532/132761000-9db08f3a-9b07-4af4-9972-3e41ae5c28b9.png)

**Comment by zheng-yuwei** [comment]
@yushuinanrong 
你看下fid的曲线，如果fid比较小，说明真人人脸域迁移到动漫人脸域的效果已经比较好了。
关于迁移后语义上的一致性问题：
1. 本来cycle loss只是弱约束，所以很难保证语义的强一致性；（你看你生成的图，整体在语义上还是基本一致的，但扣一下局部区域或者像素上的一致性就不够理想了）
2. 你的动漫域数据集是咋样的，生成的动漫人脸就是咋样的。除了一致性外，单拎出来放到原始动漫数据集里能不能混淆你也是一个重要的mos评价指标（个人看法）。

所以，要看fid~~

---

效果的话，如果要提高一致性（像我博客的效果那样），最好是保证：

1. 真人人脸和动漫人脸的对齐方式是一致的；
2. 动漫人脸的人脸分布（表情、角度）比较丰富；
3. 动漫域的风格一致，且元素不要过于丰富，降低学习难度。

这个更多是数据层面上的东西了~

**Comment by yushuinanrong** [comment]
@zheng-yuwei 
了解了，多谢回复。
