### ISSUE TITLE
Typo in model_ema function?

### ISSUE THREAD

**Issue by kasim0226** [zheng-yuwei/enhanced-UGATIT#4]
Thank you for your great work.
Should `p_ema.copy_(p_ema)` to be `p_ema.copy_(p)`?

`         else:
            for p_ema, p in zip(G_ema.parameters(), G.parameters()):
                p_ema.copy_(p_ema)
`

https://github.com/zheng-yuwei/enhanced-UGATIT/blob/5294a6ffd2d6f41f4b83ae901c6edb98f02cadc6/UGATIT.py#L811

**Comment by zheng-yuwei** [comment]
yes~
