### ISSUE TITLE
About FaceSeg interpolate

### ISSUE THREAD

**Issue by zhongtao93** [zheng-yuwei/enhanced-UGATIT#5]
https://github.com/zheng-yuwei/enhanced-UGATIT/blob/5294a6ffd2d6f41f4b83ae901c6edb98f02cadc6/faceseg/FaceSegmentation.py#L54
大佬，咱就用中文提问了哈。
这里插值方式是不是 nearest 合理一些。如3和7下采样应该取3或7，而不能去3-7中间的值。

**Comment by zheng-yuwei** [comment]
这个细节我就没做过多探索了。我主要是人工视觉review几张图的分割、处理效果~感觉没什么问题

**Comment by zhongtao93** [comment]
嗯嗯，尺寸相差不大的resize影响不大。另外想请教下，如果做风格转换，但想保持背景和原图一致。用这个repo的方法可以实现么

**Comment by zheng-yuwei** [comment]
我主要是两个实现：基于增加背景约束的Region-based U-GAT-IT算法改进（也就是这个库），基于增加掩膜分支的Mask U-GAT-IT算法改进。这个库的实现应该是不全的，和我最终的实现处于很初级的阶段。但沿着这个想法去做是对的。
[移动端人脸风格化技术的应用](https://mp.weixin.qq.com/s/372fHQiBOsaslv5ZvZ5EkQ)

**Comment by zhongtao93** [comment]
视频demo很惊艳呀，前背景融合很好，尤其是额头发丝。这都是在生成数据的时候完成的融合嘛。
![image](https://user-images.githubusercontent.com/15263824/184793119-4dd84e83-9891-4a62-b8fa-9de9400af824.png)
大佬计划开源掩膜分支的Mask U-GAT-IT的部分代码么，或者分享下思路。我发现用后处理（分割+融合）始终不自然。

**Comment by zheng-yuwei** [comment]
背景约束和掩膜的差别在于 id感 和 风格化程度 上的差异而已，在融合上两者效果差不多，甚至背景约束上的效果更自然一些。
然后其实人工筛数据和数据分布很重要，数据处理后训练可以得到很完美的模型！

不会开源的，思路可能也不会分享，在阿里内网有分享。但发外网时审核删除了好多技术细节。。。
实在想看，你可以找下阿里的同学上内网ATA看看？

**Comment by zhongtao93** [comment]
感谢大佬耐心及时的回复～
我觉得大佬的code水平和算法深度，整理下发个顶会问题不大。
期待大佬的论文～
